### ISSUE TITLE
Ambiguous Truth Value Error in aperture_mask Comparison in giants/target.py

### ISSUE THREAD

**Issue by prashant050701** [nksaunders/giants#21]
@nksaunders 

Was trying the example in the readme and  library raises a ValueError when using the fetch_and_clean_data method with certain aperture_mask values. The error is pointing to an ambiguous truth value when comparing the aperture_mask parameter with the string 'center'.

```
import giants
target = giants.Target(ticid=176956893)
target.fetch_and_clean_data(sectors=[1,2])
target.create_summary_plot()

```

```
Traceback (most recent call last):
  File "/TESS_giants/test.py", line 3, in <module>
    target.fetch_and_clean_data(sectors=[1,2])
  File "/python3.11/site-packages/giants/target.py", line 524, in fetch_and_clean_data
    lc = self.from_lightkurve(sectors=sectors, flatten=flatten, aperture_mask=aperture_mask, zero_point_background=zero_point_background, n_pca=n_pca)
         
  File "/python3.11/site-packages/giants/target.py", line 183, in from_lightkurve
    elif (aperture_mask == 'center'):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by nksaunders** [comment]
Thank you for catching this issue @prashant050701! I just pushed a [commit](https://github.com/nksaunders/giants/commit/f13a8e23cd9f58875060ad87c18a898edeb4ccc3) which should resolve this by checking that the `aperture_mask` variable is a string before attempting to resolve it as a string. Please let me know if you encounter any other issues!
